# Generated by Django 3.2.4 on 2021-07-16 02:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='Street address', max_length=200)),
                ('city', models.CharField(help_text='City', max_length=200)),
                ('state', models.CharField(help_text='State', max_length=200)),
                ('country', models.CharField(default='United States', help_text='Country', max_length=200)),
                ('zipcode', models.CharField(max_length=5)),
                ('latitude', models.CharField(default='', editable=False, max_length=200)),
                ('longitude', models.CharField(default='', editable=False, max_length=200)),
                ('coordinates', models.CharField(default='', editable=False, max_length=200)),
                ('info', models.TextField(default='', editable=False)),
                ('is_home_depot', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(choices=[('PERMANENT', 'Permanent'), ('VOLUNTEER', 'Volunteer'), ('NONE', 'None')], max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('PERMANENT', 'Permanent'), ('VOLUNTEER', 'Volunteer'), ('NONE', 'None')], default='None', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('availability_score', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='Select a language', max_length=20)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cvrp.driver')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.PositiveIntegerField(default=0)),
                ('assigned', models.BooleanField(default=False, editable=False, null=True)),
                ('route_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cvrp.address')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cvrp.driver')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='language',
            field=models.ManyToManyField(help_text='Select a language', to='cvrp.Language'),
        ),
        migrations.AddField(
            model_name='address',
            name='language',
            field=models.ManyToManyField(to='cvrp.Language'),
        ),
    ]
