# Generated by Django 3.2.4 on 2021-09-15 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvrp.driver'),
        ),
        migrations.AlterField(
            model_name='route',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvrp.driver'),
        ),
    ]
