# Generated by Django 3.2.4 on 2021-09-15 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0002_auto_20210914_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvrp.address'),
        ),
    ]
