# Generated by Django 3.2.3 on 2021-05-15 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='address',
            name='created_on',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='coordinates',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.PositiveIntegerField(default=0)),
                ('assigned', models.BooleanField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cvrp.address')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cvrp.route')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
