# Generated by Django 3.2.4 on 2021-07-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0002_alter_address_is_home_depot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
    ]
