# Generated by Django 3.2.3 on 2021-05-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0002_auto_20210515_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
