# Generated by Django 3.2.3 on 2021-05-16 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0004_auto_20210515_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='availability_score',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='assigned',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='route',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='cvrp.route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='assigned_to',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='cvrp.driver'),
        ),
        migrations.AlterField(
            model_name='route',
            name='demand',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
