# Generated by Django 3.0.10 on 2021-05-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0005_auto_20210515_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French')], max_length=20)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='language',
            field=models.ManyToManyField(help_text='Select a language', to='cvrp.Language'),
        ),
    ]
