# Generated by Django 3.0.10 on 2021-05-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0008_auto_20210528_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='route',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='cvrp.Route'),
        ),
    ]
