# Generated by Django 3.0.10 on 2021-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0009_auto_20210528_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='assigned',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
    ]
