# Generated by Django 3.0.10 on 2021-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0010_auto_20210528_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='language',
            field=models.ManyToManyField(help_text='Select a language', to='cvrp.Language'),
        ),
    ]
