# Generated by Django 3.0.10 on 2021-05-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0011_driver_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(help_text='Select a language', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='language',
            field=models.ManyToManyField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French')], help_text='Select a language', to='cvrp.Language'),
        ),
    ]
