# Generated by Django 3.0.10 on 2021-05-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0012_auto_20210528_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='language',
            field=models.ManyToManyField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('Chinese', 'Chinese'), ('Hindi', 'Hindi')], help_text='Select a language', to='cvrp.Language'),
        ),
    ]
