# Generated by Django 3.0.10 on 2021-06-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0014_auto_20210528_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('VOLUNTEER', 'Volunteer'), ('NONE', 'None')], max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cvrp.Route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cvrp.Driver'),
        ),
        migrations.AlterField(
            model_name='route',
            name='demand',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
