# Generated by Django 3.2.4 on 2021-07-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0016_auto_20210710_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='language',
        ),
        migrations.AddField(
            model_name='address',
            name='language',
            field=models.ManyToManyField(help_text='Select a language', to='cvrp.Language'),
        ),
    ]
