# Generated by Django 3.2.4 on 2021-07-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0017_auto_20210710_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='language',
            field=models.ManyToManyField(to='cvrp.Language'),
        ),
    ]
