# Generated by Django 3.2.4 on 2021-07-11 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0018_alter_address_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='route',
        ),
        migrations.AddField(
            model_name='location',
            name='route_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
