# Generated by Django 3.2.4 on 2021-07-11 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0019_auto_20210711_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='route_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
