# Generated by Django 3.2.4 on 2021-07-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvrp', '0020_alter_location_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cvrp.address'),
        ),
    ]
