# Generated by Django 3.0.10 on 2021-05-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('P', 'Permanent'), ('V', 'Volunteer'), ('N', 'None')], default='N', max_length=1)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'role'],
            },
        ),
    ]
