# Generated by Django 3.0.10 on 2021-05-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='Street address', max_length=200)),
                ('city', models.CharField(help_text='City', max_length=200)),
                ('state', models.CharField(help_text='State', max_length=200)),
                ('country', models.CharField(default='United States', help_text='Country', max_length=200)),
                ('zipcode', models.CharField(max_length=5)),
                ('latitude', models.CharField(default='', editable=False, max_length=200)),
                ('longitude', models.CharField(default='', editable=False, max_length=200)),
                ('coordinates', models.CharField(default='', max_length=200)),
                ('info', models.TextField(default='', editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
